export const DashboardArr =[
    {
        id:1,
        title:'Laptop',
        count:'40',
        category:'Electronics',
    },
    {
        id:2,
        title:'Storage Devices',
        count:'1',
        category:'Electronics',
    },
    {
        id:3,
        title:'Tables',
        count:'20',
        category:'Furniture',
    },
    {
        id:4,
        title:'Chairs',
        count:'30',
        category:'Furniture',
    },
    {
        id:5,
        title:'Camera',
        count:'10',
        category:'Electronics',
    },
    {
        id:6,
        title:'Televisions',
        count:'2',
        category:'Electronics',
    }
];



export const cardsArr = [
    {
      id: 1,
      title: "No of Inquiries",
      path: "inquiry",
      content: {
        username: "Username",
        email: "Email",
        number: "Number",
        service: "Service",
        enterYourText: "Text",
      },
    },
    {
      id: 2,
      title: "No of Quotation",
      path: "quotation",
      content: {
        username: "Username",
        email: "Email",
        number: "Number",
        service: "Service",
        enterYourText: "Text",
      },
    },
    {
      id: 3,
      title: "No of Customer",
      path: "customer",
      content: {
        username: "Username",
        email: "Email",
        number: "Number",
        service: "Service",
        enterYourText: "Text",
      },
    }
  ];







  export const companiesArr = {
    zPlusSecurity: {
      companyName: "Z plus security",
      date: "23 Aug 2024",
      to: {
        companyName: "Odisha Udyog Infra Projects",
        address: [
          "Plot No-687/2365, Jayadev Vihar, PS- Nayapalli",
          "Bhubaneswar Khordha-751015"
        ],
      },
      services: {
        eightHourService: {
          title: "8 Hrs Per day - Z+ Security - Category",
          costDetails: [
            { costHead: "Minimum wages Per Day", particulars: "As per State Minimum Wages", securityGuardSemiSkilled: 500, securitySupervisorSkilled: 550 },
            { costHead: "Minimum Wage for 26 days", particulars: "", securityGuardSemiSkilled: 13000, securitySupervisorSkilled: 14300 },
            { costHead: "Special Allowance", particulars: "", securityGuardSemiSkilled: null, securitySupervisorSkilled: 800 },
            { costHead: "Gross", particulars: "", securityGuardSemiSkilled: 13000, securitySupervisorSkilled: 15100 },
            { costHead: "Provident Fund on Basic", particulars: "13.00%", securityGuardSemiSkilled: 1690, securitySupervisorSkilled: 1859 },
            { costHead: "ESI on Gross 3.25%", particulars: "3.25%", securityGuardSemiSkilled: 423, securitySupervisorSkilled: 491 },
            { costHead: "Gratuity", particulars: "4.81%", securityGuardSemiSkilled: 625, securitySupervisorSkilled: 688 },
            { costHead: "Bonus 8.33% on MW", particulars: "8.33%", securityGuardSemiSkilled: 1083, securitySupervisorSkilled: 1191 },
            { costHead: "Uniform", particulars: "", securityGuardSemiSkilled: 500, securitySupervisorSkilled: 500 },
            { costHead: "Leave and N&F Holiday Wages (24 days per year)", particulars: "", securityGuardSemiSkilled: 867, securitySupervisorSkilled: 1007 },
            { costHead: "Sub Total A", particulars: "", securityGuardSemiSkilled: 5187, securitySupervisorSkilled: 5735 },
            { costHead: "CTC", particulars: "", securityGuardSemiSkilled: 18187, securitySupervisorSkilled: 20835 },
            { costHead: "Reliever Cost 16.67%", particulars: "16.67%", securityGuardSemiSkilled: 3032, securitySupervisorSkilled: 3473 },
            { costHead: "Sub Total B", particulars: "", securityGuardSemiSkilled: 21219, securitySupervisorSkilled: 24309 },
            { costHead: "ACCOMMODATION", particulars: "", securityGuardSemiSkilled: 700, securitySupervisorSkilled: 1000 },
            { costHead: "Sub Total C", particulars: "", securityGuardSemiSkilled: 21919, securitySupervisorSkilled: 25309 },
            { costHead: "Service Charges 10%", particulars: "10%", securityGuardSemiSkilled: 2192, securitySupervisorSkilled: 2531 },
            { costHead: "Total", particulars: "", securityGuardSemiSkilled: 24111, securitySupervisorSkilled: 27840 },
            { costHead: "Price for 8 hrs PM", particulars: "", securityGuardSemiSkilled: 24111, securitySupervisorSkilled: 27840 },
            { costHead: "Price for 8 hrs PD", particulars: "", securityGuardSemiSkilled: 793, securitySupervisorSkilled: 915 },
          ],
        },
        twelveHourService: {
          title: "12 Hrs/Per Day - Z+ Security - Category",
          costDetails: [
            { costHead: "Minimum wages Per Day", particulars: "As per State Minimum Wages", securityGuardSemiSkilled: 500, securitySupervisorSkilled: 550 },
            { costHead: "Minimum Wage for 26 days", particulars: "", securityGuardSemiSkilled: 13000, securitySupervisorSkilled: 14300 },
            { costHead: "Special Allowance", particulars: "", securityGuardSemiSkilled: 6500, securitySupervisorSkilled: 7150 },
            { costHead: "Gross", particulars: "", securityGuardSemiSkilled: 19500, securitySupervisorSkilled: 21450 },
            { costHead: "Provident Fund on Basic", particulars: "13.00%", securityGuardSemiSkilled: 1690, securitySupervisorSkilled: 1859 },
            { costHead: "ESI on Gross 3.25%", particulars: "3.25%", securityGuardSemiSkilled: 423, securitySupervisorSkilled: 697 },
            { costHead: "Gratuity", particulars: "4.81%", securityGuardSemiSkilled: 625, securitySupervisorSkilled: 688 },
            { costHead: "Bonus 8.33% on MW", particulars: "8.33%", securityGuardSemiSkilled: 1083, securitySupervisorSkilled: 1191 },
            { costHead: "Uniform", particulars: "", securityGuardSemiSkilled: 500, securitySupervisorSkilled: 500 },
            { costHead: "Leave and N&F Holiday Wages (24 days per year)", particulars: "", securityGuardSemiSkilled: 867, securitySupervisorSkilled: 1007 },
            { costHead: "Sub Total A", particulars: "", securityGuardSemiSkilled: 6915, securitySupervisorSkilled: 7992 },
            { costHead: "CTC", particulars: "", securityGuardSemiSkilled: 26415, securitySupervisorSkilled: 29442 },
            { costHead: "Reliever Cost 16.67%", particulars: "16.67%", securityGuardSemiSkilled: 0, securitySupervisorSkilled: 0 },
            { costHead: "Sub Total B", particulars: "", securityGuardSemiSkilled: 26415, securitySupervisorSkilled: 29442 },
            { costHead: "ACCOMMODATION", particulars: "", securityGuardSemiSkilled: 700, securitySupervisorSkilled: 1000 },
            { costHead: "Sub Total C", particulars: "", securityGuardSemiSkilled: 27115, securitySupervisorSkilled: 30442 },
            { costHead: "Service Charges 10%", particulars: "10%", securityGuardSemiSkilled: 2711, securitySupervisorSkilled: 3044 },
            { costHead: "Total", particulars: "", securityGuardSemiSkilled: 29826, securitySupervisorSkilled: 33486 },
            { costHead: "Price for 12 hrs PM", particulars: "", securityGuardSemiSkilled: 29826, securitySupervisorSkilled: 33486 },
            { costHead: "Price for 12 hrs PD", particulars: "", securityGuardSemiSkilled: 993, securitySupervisorSkilled: 1116 },
          ],
        },
      },
      termsAndConditions: {
        points: [
          "All prices are exclusive of GST.",
          "This quotation is valid for 30 days.",
          "Payment terms: 50% advance and 50% on completion.",
        ],
      },
    },
    mrCorporate: {
      companyName: "Mr. Corporate",
      cost_head: {
        hours_per_month: "12",
        security_guard: {
          role: "Semi Skilled",
          minimum_wages_per_day: 500,
          minimum_wages_for_26_days: 13000,
          "4_hours_calculation": 6500,
          gross: 19500,
          provident_fund_on_basic: { percentage: "13%", amount: 1690 },
          esi_on_gross: { percentage: "3.25%", amount: 423 },
          gratuity: { percentage: "4.81%", amount: 625 },
          bonus: { percentage: "8.33%", amount: 1083 },
          leave: { days_per_year: 24, amount: 867 },
          uniform_cost: 500,
          accommodation_cost: 500,
          sub_total_a: 5687,
          ctc: 25187,
          reliever_cost: { percentage: "16.67%", amount: 4198 },
          sub_total_b: 29385,
          service_charges: { percentage: "10%", amount: 2939 },
          total: 32324,
          price_per_12_hours_pm: 32324,
          price_per_12_hours_pd: 1077,
        },
        security_supervisor: {
          role: "Skilled",
          minimum_wages_per_day: 550,
          minimum_wages_for_26_days: 14300,
          "4_hours_calculation": 7150,
          gross: 21450,
          provident_fund_on_basic: { percentage: "13%", amount: 1859 },
          esi_on_gross: { percentage: "3.25%", amount: 697 },
          gratuity: { percentage: "4.81%", amount: 688 },
          bonus: { percentage: "8.33%", amount: 1191 },
          leave: { days_per_year: 24, amount: 953 },
          uniform_cost: 500,
          accommodation_cost: 500,
          sub_total_a: 6388,
          ctc: 27838,
          reliever_cost: { percentage: "16.67%", amount: 4640 },
          sub_total_b: 32478,
          service_charges: { percentage: "10%", amount: 3248 },
          total: 35726,
          price_per_12_hours_pm: 35726,
          price_per_12_hours_pd: 1191,
        },
        security_officer: {
          role: "High Skilled",
          minimum_wages_per_day: 600,
          minimum_wages_for_26_days: 15600,
          gross: 23400,
          provident_fund_on_basic: { percentage: "13%", amount: 2028 },
          esi_on_gross: { percentage: "3.25%", amount: 761 },
          gratuity: { percentage: "4.81%", amount: 750 },
          bonus: { percentage: "8.33%", amount: 1299 },
          leave: { days_per_year: 24, amount: 1040 },
          uniform_cost: 500,
          accommodation_cost: 500,
          sub_total_a: 6878,
          ctc: 30278,
          reliever_cost: { percentage: "16.67%", amount: 5046 },
          sub_total_b: 35325,
          service_charges: { percentage: "10%", amount: 3532 },
          total: 38857,
          price_per_12_hours_pm: 38857,
          price_per_12_hours_pd: 1295,
        },
      },
      note: [
        "Terms & Conditions:",
        "QUOTATION FOR MANPOWER SERVICES",
        "Accommodation cost is inclusive if client is not providing.",
        "GST 18% extra applicable as per Govt notification",
        "The Billing rate will be revised according to the Govt. notification",
        "Above quoted rate including statutory compliances.",
      ],
    },
    utkalFacility: {
      companyName: "Utkal Facility Services Pvt. Ltd.",
      services: {
        security_guard: {
          role: "Semi Skilled",
          minimum_wages_per_day: 500,
          minimum_wages_for_26_days: 13000,
          gross: 13000,
          provident_fund_on_basic: { percentage: "13.00%", amount: 1690 },
          esi_on_gross: { percentage: "3.25%", amount: 423 },
          gratuity: { percentage: "4.81%", amount: 625 },
          bonus: { percentage: "8.33%", amount: 1083 },
          uniform_cost: 500,
          accommodation_cost: 500,
          leave: { days_per_year: 24, amount: 867 },
          sub_total_a: 5687,
          ctc: 18687,
          reliever_cost: { percentage: "16.67%", amount: 3115 },
          sub_total_b: 21803,
          service_charges: { percentage: "10%", amount: 2180 },
          total: 23983,
          price_per_8_hours_pm: 23983,
          price_per_8_hours_pd: 788,
        },
        security_supervisor: {
          role: "Skilled",
          minimum_wages_per_day: 550,
          minimum_wages_for_26_days: 14300,
          gross: 15100,
          provident_fund_on_basic: { percentage: "13.00%", amount: 1859 },
          esi_on_gross: { percentage: "3.25%", amount: 491 },
          gratuity: { percentage: "4.81%", amount: 688 },
          bonus: { percentage: "8.33%", amount: 1191 },
          uniform_cost: 500,
          accommodation_cost: 500,
          leave: { days_per_year: 24, amount: 953 },
          sub_total_a: 6182,
          ctc: 21282,
          reliever_cost: { percentage: "16.67%", amount: 3548 },
          sub_total_b: 24830,
          service_charges: { percentage: "10%", amount: 2483 },
          total: 27313,
          price_per_12_hours_pm: 27313,
          price_per_12_hours_pd: 898,
        },
        security_officer: {
          role: "High Skilled",
          minimum_wages_per_day: 600,
          minimum_wages_for_26_days: 15600,
          gross: 17100,
          provident_fund_on_basic: { percentage: "13.00%", amount: 2028 },
          esi_on_gross: { percentage: "3.25%", amount: 556 },
          gratuity: { percentage: "4.81%", amount: 750 },
          bonus: { percentage: "8.33%", amount: 1299 },
          uniform_cost: 500,
          accommodation_cost: 500,
          leave: { days_per_year: 24, amount: 1040 },
          sub_total_a: 6878,
          ctc: 30278,
          reliever_cost: { percentage: "16.67%", amount: 5046 },
          sub_total_b: 35326,
          service_charges: { percentage: "10%", amount: 3533 },
          total: 38858,
          price_per_12_hours_pm: 38858,
          price_per_12_hours_pd: 1278,
        },
      },
      note: [
        "Accommodation cost is inclusive if client is not providing.",
        "Above quoted rate including statutory compliances.",
        "GST 18% extra applicable as per Govt notification",
        "The Billing rate will be revised according to the Govt. notification.",
      ],
    },
  };
  